services:
    client:
        build: ./client
        depends_on:
            - server
        env_file:
            - .env
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules/
            - /app/.next/
    server:
        build: ./server
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - 3010:3010 # HTTP
            - 3020:3020 # WS
        volumes:
            - /app/node_modules/
    database:
        image: mongo:8
        command: ["mongod", "--auth"]
        env_file:
            - .env
        volumes:
            - ./database/data:/data/db
            - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        expose:
            - 27017
