services:
    client:
        build: ./client
        depends_on:
            - server
        ports:
            - 4000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/.next
    server:
        build: ./server
        depends_on:
            - database
        environment:
            - PORT=4030
            - WSPORT=4040
            - MONGODB_USER=root
            - MONGODB_PASSWORD=root
            - MONGODB_DATABASE=Connect4
            - MONGODB_URL=mongodb://root:root@database:27017/Connect4?authSource=Connect4
        ports:
            - 4030:4030
            - 4040:4040
        volumes:
            - ./server:/app
            - /app/node_modules
    database:
        image: mongo:latest
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: Connect4
        volumes:
            - ./database/data:/data/db
            - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        expose:
            - 27017
