version: "3.8"
services:
    client:
        build: ./client
        depends_on:
            - server
        ports:
            - 4000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/.next
    server:
        build: ./server
        depends_on:
            - database
        environment:
            - PORT=4030
            - WSPORT=4040
            - MONGODB_USER=root
            - MONGODB_PASSWORD=root
            - MONGODB_DATABASE=Connect4
            - MONGODB_URL=mongodb://root:root@database:27017/Connect4?authSource=admin
        ports:
            - 4030:4030
            - 4040:4040
        volumes:
            - ./server:/app
            - /app/node_modules
    database:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=Connect4
        volumes:
            - ./database/data:/data/db
        expose:
            - 27017
