version: "3.8"
services:
    client:
        build: /client
        depends_on:
            - server
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/.next
    server:
        build: /server
        environment:
            - PORT=3030
        ports:
            - 3030:3030
        volumes:
            - ./server:/app
            - /app/node_modules
