version: "3.8"
services:
    client:
        build: /client
        depends_on:
            - server
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
            - /app/.next
    server:
        build: /server
        depends_on:
            - database
        environment:
            - PORT=3030
            - WSPORT=3040
            - MONGODB_USER=admin
            - MONGODB_PASSWORD="root"
            - MONGODB_DATABASE=Connect4
            - MONGODB_URL=mongodb://admin:root@database:27017/Connect4?authMechanism=DEFAULT&authSource=admin
        ports:
            - 3030:3030
            - 3040:3040
        volumes:
            - ./server:/app
            - /app/node_modules
    database:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=Connect4
        volumes:
            - ./database/data:/data/db
        ports:
            - 27017:27017
        expose:
            - 27017
